{
 "title": "K6 Test Results flux",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "testid",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: v.defaultBucket, tag: \"testid\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Total requests count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"browser_http_req_duration\")\n  |> count()\n  |> group()\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "P95 Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"browser_http_req_duration\")\n  |> filter(fn: (r) => r[\"testid\"] =~ /${testid:regex}/)\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> quantile(q: 0.95, method: \"exact_mean\")"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"browser_data_received\")\n  |> filter(fn: (r) => r[\"testid\"] =~ /${testid:regex}/)\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> sum()"
    }
   ]
  },
  {
   "title": "Data Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"browser_data_sent\")\n  |> filter(fn: (r) => r[\"testid\"] =~ /${testid:regex}/)\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> sum()"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "// Count of actions by type with friendly names as labels\nfrom(bucket: \"k6bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"user_action\")\n  |> keep(columns: [\"_time\", \"_value\", \"step\", \"action\", \"button\"])\n  |> group(columns: [\"step\", \"action\", \"button\"])\n  |> count()\n  |> map(fn: (r) => ({ r with _time: now() }))\n  // Map friendly names\n  |> map(fn: (r) => {\n      friendlyName = if r.button == \"accept_cookies\" then \"Accept Cookies\"\n                     else if r.button == \"login_submit\" then \"Login Button\" \n                     else if r.action == \"page_navigation\" then \"Page Navigation\"\n                     else \"${r.step}: ${r.action}\"\n      return { r with friendlyName: friendlyName }\n    })\n  |> sort(columns: [\"_value\"], desc: true)\n  |> limit(n: 100)\n  // Keep only the columns we want\n  |> keep(columns: [\"_time\", \"_value\", \"friendlyName\"])\n  |> rename(columns: {_value: \"count\", friendlyName: \"Action\"})"
    }
   ]
  },
  {
   "title": "Transactions execution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "// Track user actions count over time\nfrom(bucket: \"k6bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"user_action\")\n  // Keep only the relevant fields\n  |> keep(columns: [\"_time\", \"_value\", \"step\", \"action\", \"button\"])\n  // Group by time\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  // Add a useful column name\n  |> rename(columns: {_value: \"count\"})"
    }
   ]
  },
  {
   "title": "Active VUs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\n  |> filter(fn: (r) => r[\"testid\"] =~ /${testid:regex}/)\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.status == \"200\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vus\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => r[\"testid\"] =~ /${testid:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: 1s, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Requests Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"browser_http_req_failed\")\n  |> filter(fn: (r) => r[\"testid\"] =~ /()/)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"k6bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"browser_http_req_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"method\", \"name\", \"status\"])\n  |> count()\n  |> rename(columns: {_value: \"amount\"})\n  |> map(fn: (r) => ({r with _time: now()}))\n  |> keep(columns: [\"method\", \"name\", \"status\", \"amount\", \"_time\", \"_value\"])\n  |> group()\n  |> sort(columns: [\"method\", \"name\", \"status\"])"
    }
   ]
  },
  {
   "title": "Google Tag Manager requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 37 },
   "targets": [
    {
     "query": "import \"regexp\"\n\nfrom(bucket: \"k6bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"browser_http_req_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => regexp.matchRegexpString(r: /^https:\\/\\/www\\.googletagmanager\\.com\\//, v: r[\"name\"]))\n  |> group(columns: [\"method\", \"name\", \"status\"])\n  |> count()\n  |> rename(columns: {_value: \"amount\"})\n  |> map(fn: (r) => ({r with _time: now()}))\n  |> keep(columns: [\"method\", \"name\", \"status\", \"amount\", \"_time\"])\n  |> group()\n  |> sort(columns: [\"method\", \"name\", \"status\"])"
    }
   ]
  }
 ]
}